import './globals.css'
import NavHeader from './NavHeader';
import ClearError from './clearError';
import {ThemeProvider} from "@/components/switch-themes";

export const metadata = {
  title: 'React Base',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning className='bg-white'>
      <body className='text-sm text-slate-700'>
        <ClearError />
        <ThemeProvider defaultTheme='light'>
          <NavHeader />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
